version: "3"
services:
  mongodb:
    image: mongo:4
    restart: always
    ports:
      - 27017:27017
    # volumes:
    #   - ./mongodb:/data/db
  api:
    image: node:10
    ports:
      - 9229:9229
      - 3000:3000
    environment:
      NODE_ENV: development
      PORT: 3000
    working_dir: /app
    volumes:
     - ./api:/app/
    command: sh init.sh
    depends_on:
      - mongodb
